apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aurora

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - web-deployment.yaml
  - worker-deployment.yaml

images:
  - name: aurora-downloader
    newTag: latest
